DROP TABLE IF EXISTS GlobalNameInfo;
DROP TABLE IF EXISTS XingCharInfos;
DROP TABLE IF EXISTS XingInfos;
DROP TABLE IF EXISTS MingCharInfos;
DROP TABLE IF EXISTS MingInfos;
DROP TABLE IF EXISTS XingMingInfos;
DROP TABLE IF EXISTS XingCharRank;
DROP TABLE IF EXISTS XingRank;
DROP TABLE IF EXISTS MingCharRank;
DROP TABLE IF EXISTS MingRank;
DROP TABLE IF EXISTS XingMingRank;


CREATE TABLE IF NOT EXISTS GlobalNameInfo(
  id INT NOT NULL,
  info VARBINARY(1024) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS XingCharInfos(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  info VARBINARY(1024) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS XingInfos(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  info VARBINARY(1024) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS MingCharInfos(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  info VARBINARY(1024) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS MingInfos(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  info VARBINARY(1024) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS XingMingInfos(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  info VARBINARY(1024) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;


CREATE TABLE IF NOT EXISTS XingCharRank(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  rank INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key, rank)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS XingRank(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  rank INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key, rank)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS MingCharRank(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  rank INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key, rank)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS MingRank(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  rank INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key, rank)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS XingMingRank(
  id INT NOT NULL AUTO_INCREMENT,
  s_key CHAR(32) NOT NULL,
  rank INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (s_key, rank)
) CHARACTER SET utf8
  COLLATE utf8_general_ci;
