# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: name.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='name.proto',
  package='tiantian.name',
  serialized_pb='\n\nname.proto\x12\rtiantian.name\"y\n\x0fRawNameItemInfo\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\x12\x12\n\nmale_count\x18\x03 \x02(\x05\x12\x14\n\x0c\x66\x65male_count\x18\x04 \x02(\x05\x12\x0c\n\x04rank\x18\x05 \x02(\x05\x12\x11\n\tsum_count\x18\x06 \x02(\x05\"\xcf\x02\n\x0eGlobalNameInfo\x12\x17\n\x0fxing_char_count\x18\x01 \x02(\x05\x12\x1c\n\x14\x64iff_xing_char_count\x18\x02 \x02(\x05\x12\x12\n\nxing_count\x18\x03 \x02(\x05\x12\x17\n\x0f\x64iff_xing_count\x18\x04 \x02(\x05\x12\x17\n\x0fming_char_count\x18\x05 \x02(\x05\x12\x1c\n\x14\x64iff_ming_char_count\x18\x06 \x02(\x05\x12\x12\n\nming_count\x18\x07 \x02(\x05\x12\x17\n\x0f\x64iff_ming_count\x18\x08 \x02(\x05\x12\x17\n\x0fxing_ming_count\x18\t \x02(\x05\x12\x1c\n\x14\x64iff_xing_ming_count\x18\n \x02(\x05\x12\x14\n\x0cperson_count\x18\x0b \x02(\x05\x12\x12\n\nmale_count\x18\x0c \x02(\x05\x12\x14\n\x0c\x66\x65male_count\x18\r \x02(\x05\"e\n\nGenderInfo\x12\x11\n\tmale_rate\x18\x01 \x02(\x02\x12\x13\n\x0b\x66\x65male_rate\x18\x02 \x02(\x02\x12/\n\x08reliable\x18\x03 \x02(\x0e\x32\x17.tiantian.name.Reliable:\x04NONE\"\xb9\x01\n\x0cNameItemInfo\x12\x0c\n\x04text\x18\x01 \x02(\t\x12/\n\x08reliable\x18\x02 \x02(\x0e\x32\x17.tiantian.name.Reliable:\x04NONE\x12\x0c\n\x04rate\x18\x03 \x02(\x02\x12\x0c\n\x04rank\x18\x04 \x02(\x05\x12\x11\n\trank_rate\x18\x05 \x02(\x02\x12\x10\n\x08sum_rate\x18\x06 \x02(\x02\x12)\n\x06gender\x18\x07 \x01(\x0b\x32\x19.tiantian.name.GenderInfo*\'\n\x08Reliable\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02')

_RELIABLE = _descriptor.EnumDescriptor(
  name='Reliable',
  full_name='tiantian.name.Reliable',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=781,
  serialized_end=820,
)

Reliable = enum_type_wrapper.EnumTypeWrapper(_RELIABLE)
NONE = 0
LOW = 1
HIGH = 2



_RAWNAMEITEMINFO = _descriptor.Descriptor(
  name='RawNameItemInfo',
  full_name='tiantian.name.RawNameItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='tiantian.name.RawNameItemInfo.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='tiantian.name.RawNameItemInfo.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='male_count', full_name='tiantian.name.RawNameItemInfo.male_count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='female_count', full_name='tiantian.name.RawNameItemInfo.female_count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='tiantian.name.RawNameItemInfo.rank', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum_count', full_name='tiantian.name.RawNameItemInfo.sum_count', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=150,
)


_GLOBALNAMEINFO = _descriptor.Descriptor(
  name='GlobalNameInfo',
  full_name='tiantian.name.GlobalNameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xing_char_count', full_name='tiantian.name.GlobalNameInfo.xing_char_count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff_xing_char_count', full_name='tiantian.name.GlobalNameInfo.diff_xing_char_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xing_count', full_name='tiantian.name.GlobalNameInfo.xing_count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff_xing_count', full_name='tiantian.name.GlobalNameInfo.diff_xing_count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ming_char_count', full_name='tiantian.name.GlobalNameInfo.ming_char_count', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff_ming_char_count', full_name='tiantian.name.GlobalNameInfo.diff_ming_char_count', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ming_count', full_name='tiantian.name.GlobalNameInfo.ming_count', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff_ming_count', full_name='tiantian.name.GlobalNameInfo.diff_ming_count', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xing_ming_count', full_name='tiantian.name.GlobalNameInfo.xing_ming_count', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff_xing_ming_count', full_name='tiantian.name.GlobalNameInfo.diff_xing_ming_count', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='person_count', full_name='tiantian.name.GlobalNameInfo.person_count', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='male_count', full_name='tiantian.name.GlobalNameInfo.male_count', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='female_count', full_name='tiantian.name.GlobalNameInfo.female_count', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=153,
  serialized_end=488,
)


_GENDERINFO = _descriptor.Descriptor(
  name='GenderInfo',
  full_name='tiantian.name.GenderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='male_rate', full_name='tiantian.name.GenderInfo.male_rate', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='female_rate', full_name='tiantian.name.GenderInfo.female_rate', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reliable', full_name='tiantian.name.GenderInfo.reliable', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=490,
  serialized_end=591,
)


_NAMEITEMINFO = _descriptor.Descriptor(
  name='NameItemInfo',
  full_name='tiantian.name.NameItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='tiantian.name.NameItemInfo.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reliable', full_name='tiantian.name.NameItemInfo.reliable', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='tiantian.name.NameItemInfo.rate', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='tiantian.name.NameItemInfo.rank', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank_rate', full_name='tiantian.name.NameItemInfo.rank_rate', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum_rate', full_name='tiantian.name.NameItemInfo.sum_rate', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='tiantian.name.NameItemInfo.gender', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=594,
  serialized_end=779,
)

_GENDERINFO.fields_by_name['reliable'].enum_type = _RELIABLE
_NAMEITEMINFO.fields_by_name['reliable'].enum_type = _RELIABLE
_NAMEITEMINFO.fields_by_name['gender'].message_type = _GENDERINFO
DESCRIPTOR.message_types_by_name['RawNameItemInfo'] = _RAWNAMEITEMINFO
DESCRIPTOR.message_types_by_name['GlobalNameInfo'] = _GLOBALNAMEINFO
DESCRIPTOR.message_types_by_name['GenderInfo'] = _GENDERINFO
DESCRIPTOR.message_types_by_name['NameItemInfo'] = _NAMEITEMINFO

class RawNameItemInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RAWNAMEITEMINFO

  # @@protoc_insertion_point(class_scope:tiantian.name.RawNameItemInfo)

class GlobalNameInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GLOBALNAMEINFO

  # @@protoc_insertion_point(class_scope:tiantian.name.GlobalNameInfo)

class GenderInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENDERINFO

  # @@protoc_insertion_point(class_scope:tiantian.name.GenderInfo)

class NameItemInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NAMEITEMINFO

  # @@protoc_insertion_point(class_scope:tiantian.name.NameItemInfo)


# @@protoc_insertion_point(module_scope)
